const en = {
  'Top.Title': 'Management Console',
  'Menu.Title': 'Change Language',
  'Menu.Japanese': 'Japanese',
  'Menu.English': 'English',
  'Menu.SingOut': 'Sign Out',
  'Side.Artist': 'Artists',
  'Side.Artwork': 'Artworks',
  'Side.Order':'Orders',
  'Orderitem.Title':'OrderItems',
  'Button.Create': 'Create',
  'Button.Edit': 'Edit',
  'Button.Delete': 'Delete',
  'Button.Submit': 'Submit',
  'Button.Cancel': 'Cancel',
  'Button.Prev': 'Prev',
  'Button.Next': 'Next',
  'DeleteConfirm.Text': 'Are your sure ?',
  'DeleteConfirm.Content': 'Do you really want to delete ',
  'Label.SignIn': 'Sign In',
  'Button.SignIn': 'Sign In',
  'Label.Name': 'Name',
  'Label.Price': 'Price',
  'Label.Category': 'Category',
  'Label.HelperText': 'Please select a category',
  'Label.ChooseFile': 'Choose File',
  'Label.Search': 'Search',
  'Label.Ordered': 'Ordered',
  'Label.Delivered': 'Delivered',
  'Label.Cancelled': 'Cancelled',
  'Label.Date': 'Date',
  'Label.Customer': 'Customer',
  'Label.Address1': 'Address1',
  'Label.Address2': 'Address2',
  'Label.Country': 'Country',
  'Label.State': 'State',
  'Label.City': 'City',
  'Label.Total': 'Total',
  'Label.ItemName': 'Product Name',
  'Label.ItemPrice': 'Item_Price',
  'Label.Quantity': 'Quantity',
  'Label.Orderinfo': 'Order Information',
  'Label.ShippingAddress': 'Shipping Address',
  'Label.BillingAddress': 'Billing Address',
  'Label.ShippingDate': 'Shipping Date',
  'Label.SubTotal': 'SubTotal',
  'Label.Tax': 'Tax',
  'Option.Category': 'All Categories',
  'Label.SignUp': 'Create Account',
  'Button.SignUp': 'Create Account',
  'Confirm.TextTitle': 'Are you sure?',
  'Confirm.TextBody' : 'Do you really want to delete',
};

export default en;