const ja = {
  'Top.Title': '管理コンソール',
  'Menu.Title': '言語を変更',
  'Menu.Japanese': '日本語',
  'Menu.English': '英語',
  'Menu.SingOut': 'ログアウト',
  'Side.Artist': 'アーティスト',
  'Side.Artwork': '芸術作品',
  'Side.Order':'注文',
  'Orderitem.Title':'注文品',
  'Button.Create': '作成',
  'Button.Edit': '編集',
  'Button.Delete': '削除',
  'Button.Submit': '送信',
  'Button.Cancel': 'キャンセル',
  'Button.Prev': '前の',
  'Button.Next': '次',
  'DeleteConfirm.Text': 'よろしいですか？',
  'DeleteConfirm.Content': '本当に削除しますか ',
  'Label.SignIn': 'サインイン',
  'Button.SignIn': 'サインイン',
  'Label.Name': '名',
  'Label.Price': '価格',
  'Label.Category': 'カテゴリ',
  'Label.HelperText': 'カテゴリーを選択してください',
  'Label.ChooseFile': 'ファイルを選ぶ',
  'Label.Search': 'サーチ',
  'Label.Ordered': '注文',
  'Label.Delivered': '配信済み',
  'Label.Cancelled': 'キャンセル',
  'Label.Date': '日付',
  'Label.Customer': '顧客',
  'Label.Address1': '住所1',
  'Label.Address2': '住所2',
  'Label.Country': '国',
  'Label.State': '状態',
  'Label.City': 'シティ',
  'Label.Total': '合計',
  'Label.ItemName': '商品名',
  'Label.ItemPrice': 'アイテム価格',
  'Label.Quantity': '量',
  'Label.Orderinfo': '注文情報',
  'Label.ShippingAddress': 'お届け先の住所',
  'Label.BillingAddress': '請求先住所',
  'Label.ShippingDate': '発送日',
  'Label.SubTotal': '小計',
  'Label.Tax': '税金',
  'Option.Category': 'すべてのカテゴリ',
  'Label.SignUp': 'アカウントを作成する',
  'Button.SignUp': 'アカウントを作成する',
  'Confirm.TextTitle': '削除の確認',
  'Confirm.TextBody' : '本当に削除しますか？'
};

export default ja;