//API Endpoints
export const BASEURL_API = 'http://mbrookietraining2019adminbackend-env.mdknpzkmj7.ap-northeast-1.elasticbeanstalk.com'
export const BASEURL_ITEM_IMAGES = 'https://dg9c95ld8mycd.cloudfront.net/items/'
export const URL_GET_ALL_ITEMS = BASEURL_API+'/api/items?offset={0}'
export const URL_DELETE_ITEM = BASEURL_API+'/api/items/{0}'
export const URL_PUT_ITEM = BASEURL_API+'/api/items/{0}'
export const URL_GET_ALL_CATEGORIES = BASEURL_API+'/api/categories'
export const URL_POST_CATEGORY = BASEURL_API+'/api/categories'
export const URL_PUT_CATEGORY = BASEURL_API+'/api/categories/{0}'
export const URL_DELETE_CATEGORY = BASEURL_API+'/api/categories/{0}'
export const URL_GET_ALL_CUSTOMERS = BASEURL_API+'/api/customers'